### PR TITLE
Fix typo

### LINKED ISSUE #99: snap crashes with TOTAL.COMPONENTS.ON
When SNAP is run with `TOTAL.COMPONENTS.ON`, the program crashes during the initialization of the snap.nc output-file with the error-message:
```
 NetCDF: Variable not found: set_accwdt
 NetCDF: Variable not found: set_accwdt
```

Using `TOTAL.COMPONENTS.OFF` avoids the problem.

Tested with snap version 2.1.8

### PR DESCRIPTION
**Pull request by magnusuMET**
Fixes #99

### CODE REVIEW

File: src/common/fldout_nc.f90 [hunk 1]
```diff
@@ -1219,7 +1219,7 @@ subroutine get_varids(iunit, varid, ierror)
   if (ierror /= NF90_NOERR .and. .not. ierror == NF90_ENOTVAR) return
   ierror = nf90_inq_varid(iunit, "total_wet_deposition", varid%iwdt)
   if (ierror /= NF90_NOERR .and. .not. ierror == NF90_ENOTVAR) return
-  ierror = nf90_inq_varid(iunit, "total_wet_dry_deposition", varid%accwdt)
+  ierror = nf90_inq_varid(iunit, "total_wet_deposition", varid%accwdt)
```
Comment (heikoklein) [inline src/common/fldout_nc.f90:1222]: Doesn't make sense to have total_wet_deposition in 1220 and 1222. Shouldn't it be total_acc_wet_deposition?
